FROM node:16

ENV REACT_APP_RTSP_STREAM_URL=''
ENV REACT_APP_NODE_ALERT_SERVER_URL=''
ENV REACT_APP_RTSP_NODE_SERVER_URL=''
ENV REACT_APP_PORT=''

RUN apt-get update

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json yarn.lock ./

RUN yarn install

# Bundle app source
COPY . .

RUN yarn build

EXPOSE 3000
CMD [ "yarn", "prod" ]